#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "
frontend looping_front
	bind *:80
	default_backend looping_back

backend looping_back
	balance roundrobin
	server 1582-web-01 54.165.197.161:80 check
	server 1582-web-02 34.73.118.163:80 check
" >> /etc/haproxy/haproxy.cfg

