#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

while IFS= read -r line
do
  echo -n 'The user '
  echo -n "$line" | cut -z -d ':' -f 1
  echo -n ' is part of the '
  echo -n "$line" | cut -z -d ':' -f 3
  echo -n ' gang, lives in '
  echo -n "$line" | cut -z -d ':' -f 6
  echo -n ' and rides '
  echo -n "$line" | cut -z -d ':' -f 7
  echo -n '. '
  echo -n "$line" | cut -z -d ':' -f 4
  echo -n "'s place is protected by the passcode "
  echo -n "$line" | cut -z -d ':' -f 2
  echo -n ", more info about the user here: "
  echo -n "$line" | cut -d ':' -f 5
done < /etc/passwd
