#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
iter=0
while [ $iter -lt 10 ]
do
    echo "Holberton School"
    if [ $iter -eq 8 ]
    then
        echo "Hi"
    fi
    iter=$((iter+1))
done
