#!/usr/bin/env bash
# Set an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts /tmp/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" /tmp/hosts.new
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
